name: Free Kali Linux RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Required Packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y gnupg2 wget lsb-release curl unzip

      - name: Add Kali Linux Repositories
        run: |
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list

      - name: Add Kali Linux GPG Key
        run: |
          sudo curl -fsSL https://archive.kali.org/archive-key.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kali.gpg

      - name: Install Kali Linux Tools
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver nmap metasploit-framework aircrack-ng

      - name: Setup VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "StrongVNCPass123!" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          # Create a custom startup script
          echo '#!/bin/sh
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          xfce4-session' > ~/.vnc/xstartup
          
          chmod +x ~/.vnc/xstartup
          
          vncserver :1 -geometry 1280x720

      - name: Download NGROK
        run: |
          # Direct download of NGROK
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xzf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok

      - name: Authenticate NGROK
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ./ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Start NGROK Tunnel
        run: |
          nohup ./ngrok tcp 5901 &
          sleep 5  # Give ngrok a moment to establish connection

      - name: Display Connection Info
        run: |
          echo "VNC Server is running. Connection details:"
          curl -s localhost:4040/api/tunnels | jq '.tunnels[0].public_url'

      - name: Keep Workflow Alive
        run: |
          # Prevent workflow from timing out
          while true; do sleep 1h; done
