name: Free Kali Linux RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Required Packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y gnupg2 wget lsb-release curl unzip

      - name: Add Kali Linux Repositories
        run: |
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list

      - name: Add Kali Linux GPG Key
        run: |
          sudo curl -fsSL https://archive.kali.org/archive-key.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kali.gpg

      - name: Install Kali Linux Tools
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver nmap metasploit-framework aircrack-ng

      - name: Setup VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "yourpassword" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1 -geometry 1280x720

      - name: Download the Latest NGROK Version
        run: |
          # Download the latest NGROK release
          curl -s https://api.ngrok.com/download | jq -r '.url' | wget -O ngrok.zip -i -
          
          # Extract the downloaded zip file
          unzip ngrok.zip
          
          # Clean up the zip file
          rm ngrok.zip

          # Make the NGROK binary executable
          chmod +x ngrok

      - name: Authenticate NGROK
        run: |
          # Authenticate NGROK with the token (provided in GitHub secrets)
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start NGROK to Expose VNC Server
        run: |
          # Start NGROK to expose the VNC service (port 5901)
          nohup ./ngrok tcp 5901 &

      - name: Keep RDP Alive
        run: |
          # Keep the workflow alive to maintain the RDP session
          tail -f /dev/null
