name: Free Kali Linux RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Required Packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y gnupg2 wget lsb-release curl unzip

      - name: Add Kali Linux Repositories
        run: |
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list

      - name: Add Kali Linux GPG Key
        run: |
          sudo curl -fsSL https://archive.kali.org/archive-key.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kali.gpg

      - name: Install Kali Linux Tools
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver nmap metasploit-framework aircrack-ng

      - name: Setup VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "yourpassword" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1 -geometry 1280x720

      - name: Download and Install NGROK
        run: |
          # Download the latest NGROK from the correct source
          curl -s https://ngrok.com/download | grep -oP 'https://bin.equinox.io/c/4VmDzA7iaJY/ngrok-stable-linux-amd64.zip' | xargs wget -O ngrok.zip
          
          # Unzip the downloaded NGROK file
          unzip ngrok.zip
          chmod +x ngrok

          # Authenticate NGROK with your token
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Expose the VNC service (5901) via NGROK tunnel
          nohup ./ngrok tcp 5901 &

      - name: Keep RDP Alive
        run: |
          tail -f /dev/null  # Keep the workflow running

