name: Free Kali Linux RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Required Packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y gnupg2 wget lsb-release curl unzip

      - name: Add Kali Linux Repositories
        run: |
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list

      - name: Add Kali Linux GPG Key
        run: |
          sudo curl -fsSL https://archive.kali.org/archive-key.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kali.gpg

      - name: Install Kali Linux Tools
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver nmap metasploit-framework aircrack-ng

      - name: Setup VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "yourpassword" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1 -geometry 1280x720

      - name: Setup NGROK for RDP
        run: |
          # Download the latest NGROK from the official source
          wget https://ngrok.com/download -O ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok

          # Use the NGROK authentication token from GitHub Secrets
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Expose the VNC service via NGROK tunnel
          nohup ./ngrok tcp 5901 &

      - name: Keep RDP Alive
        run: |
          tail -f /dev/null  # Keep the workflow running
