name: Free Kali Linux RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Required Packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y gnupg2 wget lsb-release curl unzip

      - name: Add Kali Linux Repositories
        run: |
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list

      - name: Add Kali Linux GPG Key
        run: |
          sudo curl -fsSL https://archive.kali.org/archive-key.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kali.gpg

      - name: Install Kali Linux Tools
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver nmap metasploit-framework aircrack-ng

      - name: Setup VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "yourpassword" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1 -geometry 1280x720

      - name: Download and Install NGROK
        run: |
          # Download the NGROK binary directly
          echo "Downloading NGROK..."
          curl -Lo ngrok https://bin.equinox.io/c/4VmDzA7iaJY/ngrok-stable-linux-amd64

          # Check if the download was successful
          if [ ! -f ngrok ]; then
            echo "NGROK download failed, please check the URL or try again later."
            exit 1
          fi

          # Make NGROK executable
          chmod +x ngrok

          # Authenticate NGROK with your token from GitHub secrets
          echo "Authenticating NGROK..."
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

          # Start NGROK to expose VNC service (port 5901)
          nohup ./ngrok tcp 5901 &

      - name: Keep RDP Alive
        run: |
          tail -f /dev/null  # Keep the workflow running to maintain the RDP connection
