name: Free Kali Linux RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Required Packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y gnupg2 wget lsb-release curl

      - name: Add Kali Linux Repositories
        run: |
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee -a /etc/apt/sources.list

      - name: Add Kali Linux GPG Key
        run: |
          sudo curl -fsSL https://archive.kali.org/archive-key.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kali.gpg

      - name: Install Kali Linux Tools
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver kali-linux-top10  # This will install Kali's top 10 tools

      - name: Setup VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "yourpassword" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1 -geometry 1280x720

      - name: Setup NGROK for RDP
        run: |
          wget https://raw.githubusercontent.com/amityadav100/Free-RDP/main/ngrok.sh && chmod +x ngrok.sh
          nohup ./ngrok.sh > ngrok.log 2>&1 &  # Run NGROK in the background

      - name: Keep RDP Alive
        run: |
          tail -f /dev/null  # This will keep the workflow running

